name: Codecov for WebRTC C SDK
on:
  push:
    branches:
      - cbmc
  pull_request:
    branches:
      - develop
      - master
jobs:
  cbmc:
    runs-on: ubuntu-20.04
    env:
      AWS_KVS_LOG_LEVEL: 2
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Install dependencies
        run: |
          sudo apt clean && sudo apt update
          sudo apt-get -y install cbmc
      - name: Build repository
        run: |
          sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6'
          mkdir build && cd build
          cmake .. -DBUILD_SAMPLE=ON
          make
          ulimit -c unlimited -S
      - name: Run CBMC checker
        run:  |
          FAILED=0
          INCLUDE_DIRS=("-Isrc/include/") 
          DIRECTORIES=("src/source/" "samples/")  # Replace with your directories
          for dir in "${DIRECTORIES[@]}"; do
            for file in $(find "$dir" -name '*.c'); do
              cbmc "${INCLUDE_DIRS[@]}" "$file" --unwind 10 --unwinding-assertions --no-unwinding-assertions || FAILED=1
            done
          done
          exit $FAILED